// before upload:
// (1) remember to add libraries containing the below three .h files:
//    Sketch - Import Library - Add Library
// the libraries will be placed in
//  Documents\Arduino\libraries
// NB: when a file is changed the corresponding library has to been added again
// (2) Remember
// Tools - Board - Arduino Due (Programming Port)
// Tools - Port - COM4 (Arduino Due (Programming Port))
// check that  "Serial.begin(115200)" below agree with baud on terminal
// (3) remember: max voltage 50, max current 5
#include <Joint.h>
// main file
#include <Utility.h>
// sat and sign function
#include <looptime.h>
// set time in loop
// Arduino stuff generated by windows
//#include <address.h>
//#include <adk.h>
//#include <confdescparser.h>
//#include <hid.h>
//#include <hidboot.h>
//#include <hidusagestr.h>
//#include <KeyboardController.h>
//#include <MouseController.h>
//#include <parsetools.h>
//#include <Usb.h>
//#include <usb_ch9.h>
// Definitions
#define SAMPLINGTIME 0.005
// s
#define ENABLEPENDUL 50
#define ENABLESLED 48
// Create joint objects
Joint sled
(
1
,
SAMPLINGTIME
);
Joint pend1
(
2
,
SAMPLINGTIME
);
Joint pend2
(
3
,
SAMPLINGTIME
);
// Setup system
void
setup
() {
// HACK
// Pin 34 needs to be input because of external clock (Remove when corrected)
pinMode
(
34
,
INPUT
);
////////////////////////
// Setup Serial
///////////////////////
//Serial.begin(9600);
Serial
.
begin
(
115200
);
// to be able to do Serial.print and still have time in loop
////////////////////////
// Setup pin modes
////////////////////////